{% set name = "click-loglevel" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a0a623fbe35d87f65ae266f8ab27dcc7e7de1015c0b2bdca45c57f3ef01f61f5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<310]

requirements:
  host:
    - hatchling
    - pip
    - python
  run:
    - python
    - click >=8

test:
  requires:
    - anyio
    - pip
    - pytest
    - pytest-cov
    - trio
  source_files:
    - test
    - tox.ini
  imports:
    - click_loglevel
  commands:
    - pip check
    - python -m pytest -vv test --ignore=test/test_with_asyncclick.py

about:
  home: https://github.com/jwodder/click-loglevel
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Log level parameter type for Click
  description: |
    `click-loglevel` provides a `LogLevel` parameter type for use in Click
    programs that wish to let the user set the logging level.  It accepts all
    of the `logging` log level names (`CRITICAL`, `ERROR`, `WARNING`, `INFO`,
    `DEBUG`, and `NOTSET`, all case insensitive), and converts them into their
    corresponding numeric values.  It also accepts integer values and leaves
    them as-is.  Custom log levels are also supported.
  dev_url: https://github.com/jwodder/click-loglevel
  doc_url: https://github.com/jwodder/click-loglevel

extra:
  recipe-maintainers:
    - jwodder
